### ISSUE TITLE
[BUG] Setup instructions is missing hbotrc step

### ISSUE THREAD

**Issue by martinkou** [pkweitai/hummingbotAI#7]
When the current installation instruction is followed, starting aihbot.py will result in the following error

```
(hummingbot-ai) martin_kou@dweomerheart:~/Development/hummingbotAI$ python aihbot.py 
Traceback (most recent call last):
  File "/home/martin_kou/Development/hummingbotAI/aihbot.py", line 13, in <module>
    from hbotrc import BotListener
ModuleNotFoundError: No module named 'hbotrc'
```

This is caused by the missing installation instructions for the `hbotrc` package - which is included in the [hbot-remote-client @ 5fa09e9](https://github.com/hummingbot/hbot-remote-client-py/tree/5fa09e966f41593cdbc6c183a2d19f43ab4880c2) submodule.

The setup instructions should include the following additional steps:

1. `git submodule update --init` to fetch the submodule;
2. `cd hbot-remote-client && pip install .` to install hbotrc from the submodule.

**Comment by pkweitai** [comment]
updated readme. thanks!
